### ISSUE TITLE
无法上拉刷新

### ISSUE THREAD

**Issue by fouriertry** [powyin/refresh#2]
无法上拉加载更多，不如说上拉根本没反应

**Comment by t894924815** [comment]
Update 不如说recyclerview的滑动事件被屏蔽了

**Comment by powyin** [comment]
是  mulitypeAdapter 的话     上拉加载 只有在有足够item 的时候才会显示

swipeNest   和  swipeRefresh 也一样的      你要确保里面有足够内容

**Comment by powyin** [comment]
更新 版本   新版本有大调整  SwipeNest 有很大优化

**Comment by powyin** [comment]
#
